package com.example.myjob.feature.navigation

sealed class Screen(val route:String) {
    object recordScreen : Screen("record_screen")
    object HomeScreen : Screen("home_screen")
    object UpdateDetailsScreen : Screen("update_detail_screen")
    object ValidateProfileCompanyScreen : Screen("validate_profile_company_screen")
    object ValidateDocCandidateScreen : Screen("validate_doc_candidate_screen")
    object ValidateProfileCandidateScreen : Screen("validate_profile_candidate_screen")
    object DetailInvitationScreen : Screen("detail_invitation_screen")
    object NormalDetailInvitationScreen : Screen("normal_detail_invitation_screen")
    object FilteredHome : Screen("filtered_home_screen")
    object SearchWordScreen : Screen("search_screen")
    object CompanyProfileForm : Screen("company_new_form_screen")

    object DemandMarketScreen : Screen("demand_market_screen")
    object DemandServiceScreen : Screen("demand_service_screen")
    object DemandMarketDetailScreen : Screen("demand_market_detail_screen")
    object FormMarketScreen : Screen("add_demand_market_screen")
    object PostScreen : Screen("post_screen")
    object CandidatePostScreen : Screen("candidate_post_screen")
    object DetailPostScreen : Screen("detail_post_screen")
    object HomeCompanyScreen : Screen("home_company_screen")
    object InvitationScreen : Screen("invitation_screen")
    object InvitationBoostScreen : Screen("invitation_boost_screen")
    object SendInvitationScreen : Screen("send_invitation_screen")
    object SendMessageScreen : Screen("send_message_screen")
    object ListMessagesScreen : Screen("list_messages_screen")
    object InvitationCompanyScreen : Screen("company_invitation_screen")
    object NotificationCompanyScreen : Screen("company_notification_screen")
    object NotificationDemandScreen : Screen("demand_notification_screen")
    object CareerScreen : Screen("career_screen")
    object CareerFormScreen : Screen("career_form_screen")
    object EducationScreen : Screen("education_screen")
    object FilterScreen : Screen("filter_screen")
    object DetailScreen : Screen("detail_screen")
    object DetailCompanyScreen : Screen("detail_company_screen")
    object EducationFormScreen : Screen("education_form_screen")
    object PersonalFormScreen : Screen("personal_form_screen")
    object CountryCodeScreen : Screen("country_code_screen")
    object textRecognitionScreen : Screen("text_screen")
    object SettingScreen : Screen("settings_screen")
    object ProfileScreen : Screen("profile_screen")
    object FavoritesScreen : Screen("favorites_screen")
    object CompanyProfileScreen : Screen("company_profile_screen")
    object galleryScreen : Screen("gallery_screen")
    object LoginScreen : Screen("login_screen")
    object SignupScreen : Screen("signup_screen")
    object SplashScreen : Screen("splash_screen")
    object OnBoardingScreen : Screen("onboarding_screen")
    object ForgotPasswordScreen : Screen("forgot_password_screen")
    object ValidationInterviewScreen : Screen("validation_interview_screen")
}