name: Run tests

on:
  pull_request:
    branches: [develop]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grant execute permessions for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew clean testDebug

  generate-log:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Generate commit log
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "# Commit Log" > COMMIT_LOG.md
          echo "" >> COMMIT_LOG.md
          git log --pretty=format:"- %h %s (%an)" >> COMMIT_LOG.md

      - name: Commit and push log file
        run: |
          git config user.name "abdennasserAbidi"
          git config user.email "abidi.abdennasser@gmail.com"
          git add COMMIT_LOG.md
          git commit -m "chore: update commit log" || echo "No changes to commit"
          git push https://$PAT_TOKEN@github.com/abdennasserAbidi/jobdeal.git HEAD:develop

  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    if: "!contains(github.event.head_commit.message, 'bump android version')"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version, commit & push
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          FILE=./app/build.gradle.kts
          if [ ! -f "$FILE" ]; then
            echo "File not found: $FILE"
            exit 1
          fi

          # Read current version
          VERSION_CODE=$(grep "versionCode =" $FILE | awk '{print $3}')
          VERSION_NAME=$(grep "versionName =" $FILE | sed 's/.*"//;s/"//')
          echo "version code $VERSION_CODE"

          # Increment
          NEW_VERSION_CODE=$((VERSION_CODE + 1))
          echo "new version code $NEW_VERSION_CODE"
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION_NAME"
          NEW_VERSION_NAME="$MAJOR.$MINOR.$((PATCH + 1))"

          # Update file
          sed -i "s/versionCode = $VERSION_CODE/versionCode = $NEW_VERSION_CODE/" $FILE
          sed -i "s/versionName = \"$VERSION_NAME\"/versionName = \"$NEW_VERSION_NAME\"/" $FILE

          # Commit & push
          git config user.name "abdennasserAbidi"
          git config user.email "abidi.abdennasser@gmail.com"
          git add $FILE
          git commit -m "chore: bump android version to $NEW_VERSION_CODE" || echo "No changes to commit"
          git push https://$PAT_TOKEN@github.com/abdennasserAbidi/jobdeal.git HEAD:develop
          
          # Build release APK
          chmod +x gradlew
          ./gradlew clean assembleRelease


  distribute:
    name: Distribute Bundle to google play
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Version Bump
        uses: chkfung/android-version-actions@v1.2.3
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{ github.run_number }}

      - name: Grant execute permessions for gradlew
        run: chmod +x gradlew
      - name: Assemble Release Bundle
        run: ./gradlew bundleRelease